options = { "gimp_image"    : "boxy.xcf",
            "chdir"         : "../",
            "color_prefix"  : "color_",
            "mask_prefix"   : "mask_",
            "export_suffix" : ".png",
            "borderx"       : 12,
            "bordery"       : 29 }

colors =  ( "black",
            "blue",
            "brown",
            "cream",
            "cyan",
            "darkblue",
            "dots",
            "flowerpower",
            "gold",
            "gray",
            "green",
            "lava",
            "none",
            "orange",
            "petrol",
            "pink",
            "purple",
            "racing",
            "red",
            "slime",
            "tribal1",
            "tribal2",
            "warning",
            "white",
            "wood0",
            "wood1",
            "wood2",
            "wood3",
            "wood4",
            "yellow",
            "zinc" )
            
sizes = ( { "x" : 230, "y" : 431, "folder" : "boxy" },
          { "x" : 326, "y" : 431, "folder" : "boxy75" },
          { "x" : 364, "y" : 431, "folder" : "boxy85" },
          { "x" : 421, "y" : 431, "folder" : "boxy100" },
          { "x" : 301, "y" : 315, "folder" : "boxy-small" } )
